using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using VenueReservation.Domain.Models.Services;
using VenueReservation.Domain.Models.Services.ValueObjects;

namespace VenueReservation.Infrastructure.Configurations;

public class ServiceConfiguration : IEntityTypeConfiguration<Service>
{
    public void Configure(EntityTypeBuilder<Service> builder)
    {
        builder.ToTable("Services");
        builder.HasKey(s => s.Id);

        builder.Property(s => s.Id) // Configure the Id property to not be generated by the database
               .ValueGeneratedNever();

        builder.Property(s => s.Name)
               .HasConversion(n => n.Value, stringValue => ServiceName.Create(stringValue).Value)
               .IsRequired()
               .HasMaxLength(ServiceName.MaxLength);

        builder.Property(s => s.Price)
               .HasConversion(p => p.Value, decimalValue => ServicePrice.Create(decimalValue).Value)
               .IsRequired()
               .HasColumnType("decimal(18,2)");
    }
}